apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: directconnect/v1beta1/gatewayassociationproposal
  labels:
    testing.upbound.io/example-name: main
  name: sample-vpc
spec:
  forProvider:
    cidrBlock: 172.16.0.0/16
    region: us-east-1
    tags:
      Name: DemoVpc
